

name: Hello World Test

on:
  schedule:
    - cron: "*/1 * * * *"  # 每5分鐘執行
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World!"

