name: Auto Scrape Canada News

on:
  schedule:
    - cron: "*/60 * * * *"  # 每60分鐘自動執行
  workflow_dispatch:       # 手動啟動

permissions:
  contents: write  # 允許 push 回 repo

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          mkdir -p data
          python scraper.py

      - name: Commit and push news.json
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/news.json
          git commit -m "Update news.json at $(date -u)" || echo "Nothing to commit"
          git push
